title: Settings
data:
  logo: icon.webp
  site_name: JouwKlimaatkast
  meta_description: 'Duurzame retourproducten bij JouwKlimaatkast - 50% korting Profiteer van splinternieuwe producten tegen 50% van de adviesprijs!'
